ServerName localhost

Header always set Access-Control-Allow-Origin "*"
Header always set Cache-Control "public, max-age=3600"

Alias /imagery/ /var/www/imagery/

<Directory /var/www/imagery>
    Options FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>

LoadTileConfigFile /etc/renderd.conf
ModTileRenderdSocketName /run/renderd/renderd.sock
ModTileRequestTimeout 3
ModTileMissingRequestTimeout 10
